# File: k8s/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: soft-crusher
spec:
  replicas: 3
  selector:
    matchLabels:
      app: soft-crusher
  template:
    metadata:
      labels:
        app: soft-crusher
    spec:
      containers:
      - name: soft-crusher
        image: chenxingqiang/soft-crusher:latest
        ports:
        - containerPort: 8080
        env:
        - name: CONFIG_FILE
          value: "/root/config.yaml"
---
apiVersion: v1
kind: Service
metadata:
  name: soft-crusher-service
spec:
  selector:
    app: soft-crusher
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer